name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --no-save live-server
      
    - name: Validate HTML
      run: |
        # Check if HTML file exists and is valid
        if [ -f "index.html" ]; then
          echo "✅ HTML file exists"
        else
          echo "❌ HTML file missing"
          exit 1
        fi
        
    - name: Validate JavaScript
      run: |
        # Check if JS file exists and has no syntax errors
        if [ -f "GAngle_SW.js" ]; then
          echo "✅ JavaScript file exists"
          node -c GAngle_SW.js
          echo "✅ JavaScript syntax is valid"
        else
          echo "❌ JavaScript file missing"
          exit 1
        fi
        
    - name: Test basic functionality
      run: |
        # Simple smoke test
        echo "✅ Basic validation passed"
        echo "Ready for deployment"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        css: true
        
  deploy-ready:
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
    - name: Deployment check
      run: |
        echo "✅ All tests passed"
        echo "✅ Code is ready for deployment"